from mda import mda_efsm

m = mda_efsm() 

m.create() 
print('insert a cup')
m.insert_cups(1)
print('insert a cup')
m.insert_cups(1)
print('not enough funds')
m.coin(0)
print('enough funds')
m.coin(1)
print('additive 1 ')
m.additive(1)
print('additive 2')
m.additive(2)
print(m.A)
print('additive 2 again')
m.additive(2)
print(m.A)
print('cancel')
m.cancel() 
print('card')
m.card()
print('dispose drink with 2 cups left')
m.dispose_drink(1)
print('card ')
m.card()
print('dispose drink with 1 cup left')
m.dispose_drink(1)